In [29]:
import pandas as pd
pd.set_option('display.max_columns', None) # show all columns
pd.set_option('display.width', 1000)

import os
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np
from dython.nominal import associations

from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
from xgboost import XGBClassifier



data_dir = ''

def preprocess_train(df):
    ## Rename columns
    col_names = {
        'id':'id',
        'Age':'age',
        'Sex':'sex',
        'Chest pain type':'chest_pain_type',
        'BP':'bp',
        'Cholesterol':'cholesterol',
        'FBS over 120':'fbs_over_120',
        'EKG results':'ekg_results',
        'Max HR':'max_hr',
        'Exercise angina':'exercise_angina',
        'ST depression':'st_depression',
        'Slope of ST':'slope_of_st',
        'Number of vessels fluro':'number_of_vessels_fluro',
        'Thallium':'thallium',
        'Heart Disease':'heart_disease'
    }

    df = df.rename(columns=col_names)

    ## Recode target variable column to binary
    df['heart_disease'] = df['heart_disease'].replace({'Presence':1, 'Absence':0}).astype(int)


    ## Drop id column
    drop_cols = ['id']
    df = df.drop(columns=drop_cols)
    return df

def preprocess_test(df):
    ## Rename columns
    col_names = {
        'id':'id',
        'Age':'age',
        'Sex':'sex',
        'Chest pain type':'chest_pain_type',
        'BP':'bp',
        'Cholesterol':'cholesterol',
        'FBS over 120':'fbs_over_120',
        'EKG results':'ekg_results',
        'Max HR':'max_hr',
        'Exercise angina':'exercise_angina',
        'ST depression':'st_depression',
        'Slope of ST':'slope_of_st',
        'Number of vessels fluro':'number_of_vessels_fluro',
        'Thallium':'thallium',
    }

    df = df.rename(columns=col_names)

    ## Recode target variable column to binary
    # df['heart_disease'] = df['heart_disease'].replace({'Presence':1, 'Absence':0}).astype(int)


    ## Drop id column
    # drop_cols = ['id']
    # df = df.drop(columns=drop_cols)
    return df

In [2]:
df = pd.read_csv(os.path.join(data_dir, 'train.csv'))
df = preprocess_train(df)

df_test = pd.read_csv(os.
path.join(data_dir, 'test.csv'))
df_test = preprocess_test(df_test)

df.head()

   age  sex  chest_pain_type   bp  cholesterol  fbs_over_120  ekg_results  max_hr  exercise_angina  st_depression  slope_of_st  number_of_vessels_fluro  thallium  heart_disease
0   58    1                4  152          239             0            0     158                1            3.6            2                        2         7              1
1   52    1                1  125          325             0            2     171                0            0.0            1                        0         3              0
2   56    0                2  160          188             0            2     151                0            0.0            1                        0         3              0
3   44    0                3  134          229             0            2     150                0            1.0            2                        0         3              0
4   58    1                4  140          234             0            2     125                1            3.8            2                        3         3              1

# Augment Features

In [51]:
def augment_features(df):
    ## Nonlinear Features
    df['age^2'] = df['age'] ** 2
    df['age^3'] = df['age'] ** 3
    df['bp^2'] = df['bp'] ** 2
    df['cholesterol^2'] = df['cholesterol'] **2
    df['max_hr^2'] = df['max_hr']**2
    df['st_depression_log'] = df['max_hr'].apply(np.log1p)

    ## Ratios
    df['st_hr_index'] = df['st_depression'] / df['max_hr'] # dont actually think this is correct calculation
    df['bp_age_ratio'] = df['bp'] / df['age']
    df['cholesterol_age_ratio'] = df['cholesterol'] / df['age']
    df['max_hr_age_ratio'] = df['max_hr'] / df['age']


    ## Composite Scores
    df['ischemia_score'] = df['st_depression'] + df['exercise_angina'] + df['number_of_vessels_fluro']
    df['exercise_capacity_score'] = df['max_hr'] / (220 - df['age'])

    return df

In [9]:
## df with features
df_wf = augment_features(df)

In [10]:
df_wf

        age  sex  chest_pain_type   bp  cholesterol  fbs_over_120  ekg_results  max_hr  exercise_angina  st_depression  slope_of_st  number_of_vessels_fluro  thallium  heart_disease  age^2   age^3   bp^2  cholesterol^2  max_hr^2  st_depression_log  st_hr_index  bp_age_ratio  cholesterol_age_ratio  max_hr_age_raito  ischemia_score  exercise_capacity_score
0        58    1                4  152          239             0            0     158                1            3.6            2                        2         7              1   3364  195112  23104          57121     24964           5.068904     0.022785      2.620690               4.120690          2.724138             6.6                 0.975309
1        52    1                1  125          325             0            2     171                0            0.0            1                        0         3              0   2704  140608  15625         105625     29241           5.147494     0.000000      2.403846               6.250000          3.288462             0.0                 1.017857
2        56    0                2  160          188             0            2     151                0            0.0            1                        0         3              0   3136  175616  25600          35344     22801           5.023881     0.000000      2.857143               3.357143          2.696429             0.0                 0.920732
3        44    0                3  134          229             0            2     150                0            1.0            2                        0         3              0   1936   85184  17956          52441     22500           5.017280     0.006667      3.045455               5.204545          3.409091             1.0                 0.852273
4        58    1                4  140          234             0            2     125                1            3.8            2                        3         3              1   3364  195112  19600          54756     15625           4.836282     0.030400      2.413793               4.034483          2.155172             7.8                 0.771605
...     ...  ...              ...  ...          ...           ...          ...     ...              ...            ...          ...                      ...       ...            ...    ...     ...    ...            ...       ...                ...          ...           ...                    ...               ...             ...                      ...
629995   56    0                1  110          226             0            0     132                0            0.0            1                        0         7              0   3136  175616  12100          51076     17424           4.890349     0.000000      1.964286               4.035714          2.357143             0.0                 0.804878
629996   54    1                4  128          249             1            2     150                0            0.0            2                        0         3              0   2916  157464  16384          62001     22500           5.017280     0.000000      2.370370               4.611111          2.777778             0.0                 0.903614
629997   67    1                4  130          275             0            0     149                0            0.0            1                        2         7              1   4489  300763  16900          75625     22201           5.010635     0.000000      1.940299               4.104478          2.223881             2.0                 0.973856
629998   52    1                4  140          199             0            2     157                0            0.0            1                        0         6              1   2704  140608  19600          39601     24649           5.062595     0.000000      2.692308               3.826923          3.019231             0.0                 0.934524
629999   51    0                2  130          199             0            0     168                0            0.0            1                        0         3              0   2601  132651  16900          39601     28224           5.129899     0.000000      2.549020               3.901961          3.294118             0.0                 0.994083

[630000 rows x 26 columns]

# Test run with all augmented features

Produced AUC of: 0.8853076896206943

In [83]:
dep_var_name = 'heart_disease'

X = df.drop([dep_var_name], axis=1)
y = df[dep_var_name]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

[d.shape for d in [X_train, X_test, y_train, y_test]]

[(504000, 25), (126000, 25), (504000,), (126000,)]

In [33]:
param_optimal = {
    'learning_rate':0.1,
    'n_estimators':140,
    'max_depth':6,
    'min_child_weight':4,
    'gamma':0,
    'subsample':0.65,
    'colsample_bytree':0.75,
    'objective':'binary:logistic',
    'scale_pos_weight':1,
    'seed':42    
}

xgb = XGBClassifier(**param_optimal).fit(X_train, y_train)

xgb_class = xgb.predict(X_test)

xgb_auc = roc_auc_score(y_test, xgb_class)
print(f"AUC score: {xgb_auc}")

AUC score: 0.8853076896206943

Different XGBClassifier training params I saw; seems to calculate a CV score 

For whatever reason I have to feed in dataframe with `.values` to avoid a `ValueError: feature_names mismatch:` during the predict()

In [ ]:
xgb_params = {
    'objective': 'binary:logistic',
    'eval_metric': 'auc',
    'n_estimators': 2000,
    'learning_rate': 0.05,
    'max_depth': 2,
    'max_bin': 128,
    'reg_lambda': 1,
    'scale_pos_weight': 1,
    'subsample': 0.95, 
    'colsample_bytree': 0.95, 
    'grow_policy': 'depthwise',
    'tree_method': 'auto', 
    'enable_categorical': True,
    'early_stopping_rounds': 10,
    'tree_method':'hist', 
    # 'predictor': 'gpu_predictor', ## getting user warning that this param is not used
}


model = XGBClassifier(
    **xgb_params,
    verbosity=1
).fit(X_train.values, y_train.values, eval_set=[(X_train.values, y_train.values), (X_test.values, y_test.values)])

[0]	validation_0-auc:0.87536	validation_1-auc:0.87442
[1]	validation_0-auc:0.87536	validation_1-auc:0.87442
[2]	validation_0-auc:0.88504	validation_1-auc:0.88402
[3]	validation_0-auc:0.91313	validation_1-auc:0.91251

c:\Users\abhi-\miniconda3\envs\capstone2\Lib\site-packages\xgboost\callback.py:386: UserWarning: [17:41:03] WARNING: C:\miniconda3\conda-bld\xgboost-split_1764761400759\work\src\learner.cc:790:
Parameters: { "predictor" } are not used.

  self.starting_round = model.num_boosted_rounds()

[4]	validation_0-auc:0.91673	validation_1-auc:0.91614
[5]	validation_0-auc:0.91645	validation_1-auc:0.91589
[6]	validation_0-auc:0.91645	validation_1-auc:0.91589
[7]	validation_0-auc:0.91656	validation_1-auc:0.91595
[8]	validation_0-auc:0.91656	validation_1-auc:0.91595
[9]	validation_0-auc:0.91499	validation_1-auc:0.91439
[10]	validation_0-auc:0.91499	validation_1-auc:0.91439
[11]	validation_0-auc:0.91931	validation_1-auc:0.91871
[12]	validation_0-auc:0.91931	validation_1-auc:0.91871
[13]	validation_0-auc:0.92427	validation_1-auc:0.92365
[14]	validation_0-auc:0.92422	validation_1-auc:0.92359
[15]	validation_0-auc:0.92422	validation_1-auc:0.92359
[16]	validation_0-auc:0.92987	validation_1-auc:0.92940
[17]	validation_0-auc:0.92904	validation_1-auc:0.92855
[18]	validation_0-auc:0.92979	validation_1-auc:0.92942
[19]	validation_0-auc:0.93014	validation_1-auc:0.92976
[20]	validation_0-auc:0.92978	validation_1-auc:0.92930
[21]	validation_0-auc:0.93031	validation_1-auc:0.92987
[22]	validation_0-auc:0.93124	validation_1-auc:0.93090
[23]	validation_0-auc:0.93292	validation_1-auc:0.93259
[24]	validation_0-auc:0.93345	validation_1-auc:0.93311
[25]	validation_0-auc:0.93472	validation_1-auc:0.93439
[26]	validation_0-auc:0.93663	validation_1-auc:0.93620
[27]	validation_0-auc:0.93671	validation_1-auc:0.93628
[28]	validation_0-auc:0.93687	validation_1-auc:0.93642
[29]	validation_0-auc:0.93750	validation_1-auc:0.93700
[30]	validation_0-auc:0.93838	validation_1-auc:0.93793
[31]	validation_0-auc:0.93927	validation_1-auc:0.93881
[32]	validation_0-auc:0.93959	validation_1-auc:0.93912
[33]	validation_0-auc:0.94019	validation_1-auc:0.93972
[34]	validation_0-auc:0.94031	validation_1-auc:0.93983
[35]	validation_0-auc:0.94117	validation_1-auc:0.94067
[36]	validation_0-auc:0.94164	validation_1-auc:0.94116
[37]	validation_0-auc:0.94177	validation_1-auc:0.94127
[38]	validation_0-auc:0.94235	validation_1-auc:0.94181
[39]	validation_0-auc:0.94281	validation_1-auc:0.94227
[40]	validation_0-auc:0.94337	validation_1-auc:0.94284
[41]	validation_0-auc:0.94389	validation_1-auc:0.94338
[42]	validation_0-auc:0.94396	validation_1-auc:0.94347
[43]	validation_0-auc:0.94411	validation_1-auc:0.94362
[44]	validation_0-auc:0.94454	validation_1-auc:0.94402
[45]	validation_0-auc:0.94509	validation_1-auc:0.94458
[46]	validation_0-auc:0.94519	validation_1-auc:0.94466
[47]	validation_0-auc:0.94517	validation_1-auc:0.94462
[48]	validation_0-auc:0.94554	validation_1-auc:0.94500
[49]	validation_0-auc:0.94593	validation_1-auc:0.94539
[50]	validation_0-auc:0.94621	validation_1-auc:0.94566
[51]	validation_0-auc:0.94625	validation_1-auc:0.94569
[52]	validation_0-auc:0.94672	validation_1-auc:0.94617
[53]	validation_0-auc:0.94699	validation_1-auc:0.94646
[54]	validation_0-auc:0.94699	validation_1-auc:0.94644
[55]	validation_0-auc:0.94729	validation_1-auc:0.94674
[56]	validation_0-auc:0.94735	validation_1-auc:0.94680
[57]	validation_0-auc:0.94736	validation_1-auc:0.94681
[58]	validation_0-auc:0.94766	validation_1-auc:0.94713
[59]	validation_0-auc:0.94772	validation_1-auc:0.94719
[60]	validation_0-auc:0.94794	validation_1-auc:0.94741
[61]	validation_0-auc:0.94805	validation_1-auc:0.94751
[62]	validation_0-auc:0.94825	validation_1-auc:0.94771
[63]	validation_0-auc:0.94840	validation_1-auc:0.94787
[64]	validation_0-auc:0.94843	validation_1-auc:0.94790
[65]	validation_0-auc:0.94858	validation_1-auc:0.94807
[66]	validation_0-auc:0.94871	validation_1-auc:0.94820
[67]	validation_0-auc:0.94888	validation_1-auc:0.94838
[68]	validation_0-auc:0.94891	validation_1-auc:0.94841
[69]	validation_0-auc:0.94904	validation_1-auc:0.94854
[70]	validation_0-auc:0.94914	validation_1-auc:0.94864
[71]	validation_0-auc:0.94915	validation_1-auc:0.94863
[72]	validation_0-auc:0.94925	validation_1-auc:0.94873
[73]	validation_0-auc:0.94935	validation_1-auc:0.94885
[74]	validation_0-auc:0.94947	validation_1-auc:0.94897
[75]	validation_0-auc:0.94955	validation_1-auc:0.94906
[76]	validation_0-auc:0.94967	validation_1-auc:0.94917
[77]	validation_0-auc:0.94979	validation_1-auc:0.94929
[78]	validation_0-auc:0.94974	validation_1-auc:0.94924
[79]	validation_0-auc:0.94983	validation_1-auc:0.94934
[80]	validation_0-auc:0.94990	validation_1-auc:0.94942
[81]	validation_0-auc:0.95006	validation_1-auc:0.94958
[82]	validation_0-auc:0.95014	validation_1-auc:0.94967
[83]	validation_0-auc:0.95017	validation_1-auc:0.94968
[84]	validation_0-auc:0.95025	validation_1-auc:0.94977
[85]	validation_0-auc:0.95033	validation_1-auc:0.94985
[86]	validation_0-auc:0.95034	validation_1-auc:0.94986
[87]	validation_0-auc:0.95039	validation_1-auc:0.94991
[88]	validation_0-auc:0.95045	validation_1-auc:0.94998
[89]	validation_0-auc:0.95054	validation_1-auc:0.95007
[90]	validation_0-auc:0.95061	validation_1-auc:0.95014
[91]	validation_0-auc:0.95071	validation_1-auc:0.95025
[92]	validation_0-auc:0.95076	validation_1-auc:0.95030
[93]	validation_0-auc:0.95081	validation_1-auc:0.95035
[94]	validation_0-auc:0.95091	validation_1-auc:0.95046
[95]	validation_0-auc:0.95099	validation_1-auc:0.95053
[96]	validation_0-auc:0.95102	validation_1-auc:0.95056
[97]	validation_0-auc:0.95105	validation_1-auc:0.95059
[98]	validation_0-auc:0.95114	validation_1-auc:0.95069
[99]	validation_0-auc:0.95120	validation_1-auc:0.95075
[100]	validation_0-auc:0.95124	validation_1-auc:0.95079
[101]	validation_0-auc:0.95125	validation_1-auc:0.95081
[102]	validation_0-auc:0.95129	validation_1-auc:0.95085
[103]	validation_0-auc:0.95132	validation_1-auc:0.95089
[104]	validation_0-auc:0.95137	validation_1-auc:0.95093
[105]	validation_0-auc:0.95145	validation_1-auc:0.95102
[106]	validation_0-auc:0.95149	validation_1-auc:0.95105
[107]	validation_0-auc:0.95153	validation_1-auc:0.95109
[108]	validation_0-auc:0.95157	validation_1-auc:0.95114
[109]	validation_0-auc:0.95159	validation_1-auc:0.95116
[110]	validation_0-auc:0.95165	validation_1-auc:0.95122
[111]	validation_0-auc:0.95169	validation_1-auc:0.95126
[112]	validation_0-auc:0.95174	validation_1-auc:0.95131
[113]	validation_0-auc:0.95182	validation_1-auc:0.95139
[114]	validation_0-auc:0.95184	validation_1-auc:0.95141
[115]	validation_0-auc:0.95184	validation_1-auc:0.95141
[116]	validation_0-auc:0.95188	validation_1-auc:0.95146
[117]	validation_0-auc:0.95193	validation_1-auc:0.95151
[118]	validation_0-auc:0.95196	validation_1-auc:0.95155
[119]	validation_0-auc:0.95199	validation_1-auc:0.95158
[120]	validation_0-auc:0.95200	validation_1-auc:0.95159
[121]	validation_0-auc:0.95203	validation_1-auc:0.95162
[122]	validation_0-auc:0.95206	validation_1-auc:0.95165
[123]	validation_0-auc:0.95212	validation_1-auc:0.95171
[124]	validation_0-auc:0.95213	validation_1-auc:0.95173
[125]	validation_0-auc:0.95216	validation_1-auc:0.95176
[126]	validation_0-auc:0.95218	validation_1-auc:0.95178
[127]	validation_0-auc:0.95220	validation_1-auc:0.95180
[128]	validation_0-auc:0.95224	validation_1-auc:0.95184
[129]	validation_0-auc:0.95228	validation_1-auc:0.95189
[130]	validation_0-auc:0.95231	validation_1-auc:0.95190
[131]	validation_0-auc:0.95233	validation_1-auc:0.95193
[132]	validation_0-auc:0.95234	validation_1-auc:0.95194
[133]	validation_0-auc:0.95237	validation_1-auc:0.95197
[134]	validation_0-auc:0.95241	validation_1-auc:0.95201
[135]	validation_0-auc:0.95242	validation_1-auc:0.95202
[136]	validation_0-auc:0.95244	validation_1-auc:0.95204
[137]	validation_0-auc:0.95245	validation_1-auc:0.95204
[138]	validation_0-auc:0.95245	validation_1-auc:0.95205
[139]	validation_0-auc:0.95249	validation_1-auc:0.95209
[140]	validation_0-auc:0.95251	validation_1-auc:0.95211
[141]	validation_0-auc:0.95253	validation_1-auc:0.95213
[142]	validation_0-auc:0.95254	validation_1-auc:0.95214
[143]	validation_0-auc:0.95255	validation_1-auc:0.95215
[144]	validation_0-auc:0.95258	validation_1-auc:0.95218
[145]	validation_0-auc:0.95261	validation_1-auc:0.95221
[146]	validation_0-auc:0.95262	validation_1-auc:0.95223
[147]	validation_0-auc:0.95264	validation_1-auc:0.95224
[148]	validation_0-auc:0.95266	validation_1-auc:0.95226
[149]	validation_0-auc:0.95268	validation_1-auc:0.95228
[150]	validation_0-auc:0.95269	validation_1-auc:0.95230
[151]	validation_0-auc:0.95273	validation_1-auc:0.95233
[152]	validation_0-auc:0.95273	validation_1-auc:0.95234
[153]	validation_0-auc:0.95274	validation_1-auc:0.95235
[154]	validation_0-auc:0.95275	validation_1-auc:0.95236
[155]	validation_0-auc:0.95278	validation_1-auc:0.95238
[156]	validation_0-auc:0.95281	validation_1-auc:0.95241
[157]	validation_0-auc:0.95283	validation_1-auc:0.95243
[158]	validation_0-auc:0.95286	validation_1-auc:0.95246
[159]	validation_0-auc:0.95287	validation_1-auc:0.95247
[160]	validation_0-auc:0.95289	validation_1-auc:0.95249
[161]	validation_0-auc:0.95291	validation_1-auc:0.95251
[162]	validation_0-auc:0.95293	validation_1-auc:0.95252
[163]	validation_0-auc:0.95293	validation_1-auc:0.95253
[164]	validation_0-auc:0.95296	validation_1-auc:0.95255
[165]	validation_0-auc:0.95297	validation_1-auc:0.95257
[166]	validation_0-auc:0.95298	validation_1-auc:0.95258
[167]	validation_0-auc:0.95301	validation_1-auc:0.95260
[168]	validation_0-auc:0.95302	validation_1-auc:0.95261
[169]	validation_0-auc:0.95304	validation_1-auc:0.95264
[170]	validation_0-auc:0.95305	validation_1-auc:0.95265
[171]	validation_0-auc:0.95307	validation_1-auc:0.95266
[172]	validation_0-auc:0.95308	validation_1-auc:0.95268
[173]	validation_0-auc:0.95311	validation_1-auc:0.95271
[174]	validation_0-auc:0.95312	validation_1-auc:0.95271
[175]	validation_0-auc:0.95313	validation_1-auc:0.95273
[176]	validation_0-auc:0.95315	validation_1-auc:0.95275
[177]	validation_0-auc:0.95317	validation_1-auc:0.95276
[178]	validation_0-auc:0.95317	validation_1-auc:0.95277
[179]	validation_0-auc:0.95319	validation_1-auc:0.95279
[180]	validation_0-auc:0.95320	validation_1-auc:0.95280
[181]	validation_0-auc:0.95320	validation_1-auc:0.95280
[182]	validation_0-auc:0.95322	validation_1-auc:0.95282
[183]	validation_0-auc:0.95324	validation_1-auc:0.95284
[184]	validation_0-auc:0.95325	validation_1-auc:0.95285
[185]	validation_0-auc:0.95326	validation_1-auc:0.95285
[186]	validation_0-auc:0.95327	validation_1-auc:0.95287
[187]	validation_0-auc:0.95329	validation_1-auc:0.95288
[188]	validation_0-auc:0.95330	validation_1-auc:0.95290
[189]	validation_0-auc:0.95331	validation_1-auc:0.95291
[190]	validation_0-auc:0.95333	validation_1-auc:0.95292
[191]	validation_0-auc:0.95333	validation_1-auc:0.95292
[192]	validation_0-auc:0.95334	validation_1-auc:0.95293
[193]	validation_0-auc:0.95336	validation_1-auc:0.95295
[194]	validation_0-auc:0.95336	validation_1-auc:0.95296
[195]	validation_0-auc:0.95337	validation_1-auc:0.95296
[196]	validation_0-auc:0.95338	validation_1-auc:0.95297
[197]	validation_0-auc:0.95339	validation_1-auc:0.95299
[198]	validation_0-auc:0.95341	validation_1-auc:0.95300
[199]	validation_0-auc:0.95342	validation_1-auc:0.95301
[200]	validation_0-auc:0.95343	validation_1-auc:0.95301
[201]	validation_0-auc:0.95343	validation_1-auc:0.95302
[202]	validation_0-auc:0.95344	validation_1-auc:0.95303
[203]	validation_0-auc:0.95345	validation_1-auc:0.95304
[204]	validation_0-auc:0.95347	validation_1-auc:0.95305
[205]	validation_0-auc:0.95347	validation_1-auc:0.95305
[206]	validation_0-auc:0.95348	validation_1-auc:0.95306
[207]	validation_0-auc:0.95349	validation_1-auc:0.95307
[208]	validation_0-auc:0.95350	validation_1-auc:0.95309
[209]	validation_0-auc:0.95351	validation_1-auc:0.95310
[210]	validation_0-auc:0.95352	validation_1-auc:0.95311
[211]	validation_0-auc:0.95352	validation_1-auc:0.95310
[212]	validation_0-auc:0.95353	validation_1-auc:0.95311
[213]	validation_0-auc:0.95354	validation_1-auc:0.95313
[214]	validation_0-auc:0.95355	validation_1-auc:0.95314
[215]	validation_0-auc:0.95356	validation_1-auc:0.95315
[216]	validation_0-auc:0.95357	validation_1-auc:0.95316
[217]	validation_0-auc:0.95358	validation_1-auc:0.95317
[218]	validation_0-auc:0.95358	validation_1-auc:0.95317
[219]	validation_0-auc:0.95359	validation_1-auc:0.95318
[220]	validation_0-auc:0.95359	validation_1-auc:0.95318
[221]	validation_0-auc:0.95360	validation_1-auc:0.95319
[222]	validation_0-auc:0.95361	validation_1-auc:0.95320
[223]	validation_0-auc:0.95362	validation_1-auc:0.95321
[224]	validation_0-auc:0.95363	validation_1-auc:0.95322
[225]	validation_0-auc:0.95363	validation_1-auc:0.95322
[226]	validation_0-auc:0.95364	validation_1-auc:0.95322
[227]	validation_0-auc:0.95365	validation_1-auc:0.95323
[228]	validation_0-auc:0.95365	validation_1-auc:0.95323
[229]	validation_0-auc:0.95366	validation_1-auc:0.95324
[230]	validation_0-auc:0.95366	validation_1-auc:0.95324
[231]	validation_0-auc:0.95367	validation_1-auc:0.95325
[232]	validation_0-auc:0.95367	validation_1-auc:0.95326
[233]	validation_0-auc:0.95368	validation_1-auc:0.95326
[234]	validation_0-auc:0.95368	validation_1-auc:0.95327
[235]	validation_0-auc:0.95369	validation_1-auc:0.95327
[236]	validation_0-auc:0.95370	validation_1-auc:0.95328
[237]	validation_0-auc:0.95370	validation_1-auc:0.95329
[238]	validation_0-auc:0.95371	validation_1-auc:0.95330
[239]	validation_0-auc:0.95372	validation_1-auc:0.95330
[240]	validation_0-auc:0.95373	validation_1-auc:0.95331
[241]	validation_0-auc:0.95373	validation_1-auc:0.95331
[242]	validation_0-auc:0.95373	validation_1-auc:0.95331
[243]	validation_0-auc:0.95374	validation_1-auc:0.95332
[244]	validation_0-auc:0.95374	validation_1-auc:0.95332
[245]	validation_0-auc:0.95375	validation_1-auc:0.95333
[246]	validation_0-auc:0.95375	validation_1-auc:0.95334
[247]	validation_0-auc:0.95376	validation_1-auc:0.95334
[248]	validation_0-auc:0.95376	validation_1-auc:0.95334
[249]	validation_0-auc:0.95377	validation_1-auc:0.95334
[250]	validation_0-auc:0.95377	validation_1-auc:0.95335
[251]	validation_0-auc:0.95378	validation_1-auc:0.95336
[252]	validation_0-auc:0.95379	validation_1-auc:0.95336
[253]	validation_0-auc:0.95379	validation_1-auc:0.95337
[254]	validation_0-auc:0.95379	validation_1-auc:0.95337
[255]	validation_0-auc:0.95380	validation_1-auc:0.95338
[256]	validation_0-auc:0.95381	validation_1-auc:0.95339
[257]	validation_0-auc:0.95381	validation_1-auc:0.95339
[258]	validation_0-auc:0.95381	validation_1-auc:0.95339
[259]	validation_0-auc:0.95381	validation_1-auc:0.95340
[260]	validation_0-auc:0.95382	validation_1-auc:0.95340
[261]	validation_0-auc:0.95382	validation_1-auc:0.95340
[262]	validation_0-auc:0.95383	validation_1-auc:0.95341
[263]	validation_0-auc:0.95383	validation_1-auc:0.95341
[264]	validation_0-auc:0.95384	validation_1-auc:0.95342
[265]	validation_0-auc:0.95384	validation_1-auc:0.95342
[266]	validation_0-auc:0.95384	validation_1-auc:0.95342
[267]	validation_0-auc:0.95385	validation_1-auc:0.95343
[268]	validation_0-auc:0.95385	validation_1-auc:0.95343
[269]	validation_0-auc:0.95386	validation_1-auc:0.95344
[270]	validation_0-auc:0.95386	validation_1-auc:0.95344
[271]	validation_0-auc:0.95387	validation_1-auc:0.95345
[272]	validation_0-auc:0.95388	validation_1-auc:0.95345
[273]	validation_0-auc:0.95388	validation_1-auc:0.95346
[274]	validation_0-auc:0.95388	validation_1-auc:0.95346
[275]	validation_0-auc:0.95389	validation_1-auc:0.95346
[276]	validation_0-auc:0.95389	validation_1-auc:0.95347
[277]	validation_0-auc:0.95389	validation_1-auc:0.95347
[278]	validation_0-auc:0.95389	validation_1-auc:0.95347
[279]	validation_0-auc:0.95390	validation_1-auc:0.95348
[280]	validation_0-auc:0.95390	validation_1-auc:0.95348
[281]	validation_0-auc:0.95391	validation_1-auc:0.95349
[282]	validation_0-auc:0.95391	validation_1-auc:0.95349
[283]	validation_0-auc:0.95392	validation_1-auc:0.95350
[284]	validation_0-auc:0.95392	validation_1-auc:0.95350
[285]	validation_0-auc:0.95393	validation_1-auc:0.95350
[286]	validation_0-auc:0.95393	validation_1-auc:0.95351
[287]	validation_0-auc:0.95393	validation_1-auc:0.95351
[288]	validation_0-auc:0.95394	validation_1-auc:0.95351
[289]	validation_0-auc:0.95394	validation_1-auc:0.95352
[290]	validation_0-auc:0.95394	validation_1-auc:0.95352
[291]	validation_0-auc:0.95395	validation_1-auc:0.95352
[292]	validation_0-auc:0.95395	validation_1-auc:0.95353
[293]	validation_0-auc:0.95396	validation_1-auc:0.95353
[294]	validation_0-auc:0.95396	validation_1-auc:0.95354
[295]	validation_0-auc:0.95396	validation_1-auc:0.95354
[296]	validation_0-auc:0.95397	validation_1-auc:0.95354
[297]	validation_0-auc:0.95397	validation_1-auc:0.95355
[298]	validation_0-auc:0.95397	validation_1-auc:0.95355
[299]	validation_0-auc:0.95398	validation_1-auc:0.95355
[300]	validation_0-auc:0.95398	validation_1-auc:0.95356
[301]	validation_0-auc:0.95399	validation_1-auc:0.95356
[302]	validation_0-auc:0.95399	validation_1-auc:0.95357
[303]	validation_0-auc:0.95399	validation_1-auc:0.95357
[304]	validation_0-auc:0.95400	validation_1-auc:0.95358
[305]	validation_0-auc:0.95400	validation_1-auc:0.95358
[306]	validation_0-auc:0.95401	validation_1-auc:0.95358
[307]	validation_0-auc:0.95401	validation_1-auc:0.95359
[308]	validation_0-auc:0.95402	validation_1-auc:0.95359
[309]	validation_0-auc:0.95402	validation_1-auc:0.95359
[310]	validation_0-auc:0.95403	validation_1-auc:0.95360
[311]	validation_0-auc:0.95403	validation_1-auc:0.95360
[312]	validation_0-auc:0.95403	validation_1-auc:0.95361
[313]	validation_0-auc:0.95404	validation_1-auc:0.95361
[314]	validation_0-auc:0.95404	validation_1-auc:0.95361
[315]	validation_0-auc:0.95405	validation_1-auc:0.95362
[316]	validation_0-auc:0.95405	validation_1-auc:0.95362
[317]	validation_0-auc:0.95405	validation_1-auc:0.95362
[318]	validation_0-auc:0.95405	validation_1-auc:0.95362
[319]	validation_0-auc:0.95406	validation_1-auc:0.95363
[320]	validation_0-auc:0.95406	validation_1-auc:0.95363
[321]	validation_0-auc:0.95407	validation_1-auc:0.95363
[322]	validation_0-auc:0.95407	validation_1-auc:0.95364
[323]	validation_0-auc:0.95407	validation_1-auc:0.95364
[324]	validation_0-auc:0.95407	validation_1-auc:0.95364
[325]	validation_0-auc:0.95408	validation_1-auc:0.95364
[326]	validation_0-auc:0.95408	validation_1-auc:0.95365
[327]	validation_0-auc:0.95408	validation_1-auc:0.95365
[328]	validation_0-auc:0.95408	validation_1-auc:0.95365
[329]	validation_0-auc:0.95409	validation_1-auc:0.95366
[330]	validation_0-auc:0.95409	validation_1-auc:0.95366
[331]	validation_0-auc:0.95410	validation_1-auc:0.95366
[332]	validation_0-auc:0.95410	validation_1-auc:0.95367
[333]	validation_0-auc:0.95410	validation_1-auc:0.95367
[334]	validation_0-auc:0.95410	validation_1-auc:0.95367
[335]	validation_0-auc:0.95410	validation_1-auc:0.95367
[336]	validation_0-auc:0.95411	validation_1-auc:0.95367
[337]	validation_0-auc:0.95411	validation_1-auc:0.95368
[338]	validation_0-auc:0.95411	validation_1-auc:0.95368
[339]	validation_0-auc:0.95412	validation_1-auc:0.95368
[340]	validation_0-auc:0.95412	validation_1-auc:0.95368
[341]	validation_0-auc:0.95412	validation_1-auc:0.95368
[342]	validation_0-auc:0.95412	validation_1-auc:0.95369
[343]	validation_0-auc:0.95412	validation_1-auc:0.95369
[344]	validation_0-auc:0.95413	validation_1-auc:0.95369
[345]	validation_0-auc:0.95413	validation_1-auc:0.95370
[346]	validation_0-auc:0.95413	validation_1-auc:0.95370
[347]	validation_0-auc:0.95414	validation_1-auc:0.95370
[348]	validation_0-auc:0.95414	validation_1-auc:0.95370
[349]	validation_0-auc:0.95414	validation_1-auc:0.95371
[350]	validation_0-auc:0.95414	validation_1-auc:0.95371
[351]	validation_0-auc:0.95415	validation_1-auc:0.95371
[352]	validation_0-auc:0.95415	validation_1-auc:0.95371
[353]	validation_0-auc:0.95415	validation_1-auc:0.95371
[354]	validation_0-auc:0.95415	validation_1-auc:0.95372
[355]	validation_0-auc:0.95415	validation_1-auc:0.95372
[356]	validation_0-auc:0.95415	validation_1-auc:0.95372
[357]	validation_0-auc:0.95416	validation_1-auc:0.95372
[358]	validation_0-auc:0.95416	validation_1-auc:0.95373
[359]	validation_0-auc:0.95416	validation_1-auc:0.95373
[360]	validation_0-auc:0.95417	validation_1-auc:0.95373
[361]	validation_0-auc:0.95417	validation_1-auc:0.95373

# Feature Elimination

## Remove Highly Correlated Features

In [39]:
features_cat = ['sex', 'chest_pain_type', 'fbs_over_120', 'ekg_results', 'exercise_angina', 'slope_of_st', 'number_of_vessels_fluro', 'thallium']

df_cat = df[features_cat]
df_num = df.drop(features_cat, axis=1).drop(['heart_disease'], axis=1)


dep_var_name = 'heart_disease'
y = df[dep_var_name]

In [40]:
def remove_high_corr(data, thresh):
    corr_matrix = associations(dataset=data, compute_only=True)['corr'].abs()
    upper_tri=corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    to_drop = [col for col in upper_tri.columns if any(upper_tri[col]>thresh)]
    data_sub = data.drop(to_drop, axis=1)
    return data_sub, to_drop

In [41]:
df_num_nhc, high_corr_cols = remove_high_corr(df_num, 0.7)

print(f"Dropped {len(high_corr_cols)} highly correlated columns")
print(high_corr_cols)

Dropped 12 highly correlated columns
['age^2', 'age^3', 'bp^2', 'cholesterol^2', 'max_hr^2', 'st_depression_log', 'st_hr_index', 'bp_age_ratio', 'cholesterol_age_ratio', 'max_hr_age_raito', 'ischemia_score', 'exercise_capacity_score']

## Remove Near Zero Variance

In [48]:
# Performing step in isolation instead of after df No Highly Correlated
vt = VarianceThreshold(threshold=0.1)
vt.fit_transform(df_num)

cols = df_num.columns[vt.get_support()]
df_num_nnzv = df_num[cols]

cols_dropped = [col for col in df_num.columns if col not in cols]
print(f"Dropped {len(cols_dropped)} columns with near zero variance")
print(cols_dropped)



# ## Performing step after df No Highly Correlated
# vt = VarianceThreshold(threshold=0.1)
# vt.fit_transform(df_num_nhc)

# cols = df_num_nhc.columns[vt.get_support()]
# df_num_nhc_nnzv = df_num_nhc[cols]

# cols_dropped = [col for col in df_num_nhc.columns if col not in cols]
# print(f"Dropped {len(cols_dropped)} columns with near zero variance")
# print(cols_dropped)

Dropped 3 columns with near zero variance
['st_depression_log', 'st_hr_index', 'exercise_capacity_score']

# Test run with reduced features

Not reducing features had higher AUC of both

In [ ]:
# df_full = pd.concat([df_num_nhc_nnzv.reset_index(drop=True), df_cat.reset_index(drop=True), df['heart_disease']], axis=1) ## --> Produced AUC of 0.884

df_full = pd.concat([df_num_nnzv.reset_index(drop=True), df_cat.reset_index(drop=True), df['heart_disease']], axis=1)       ## --> Produced AUC of 0.8850766677434503

In [53]:
dep_var_name = 'heart_disease'

X = df_full.drop([dep_var_name], axis=1)
y = df_full[dep_var_name]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


param_optimal = {
    'learning_rate':0.1,
    'n_estimators':140,
    'max_depth':6,
    'min_child_weight':4,
    'gamma':0,
    'subsample':0.65,
    'colsample_bytree':0.75,
    'objective':'binary:logistic',
    'scale_pos_weight':1,
    'seed':42    
}

xgb = XGBClassifier(**param_optimal).fit(X_train, y_train)

xgb_class = xgb.predict(X_test)

xgb_auc = roc_auc_score(y_test, xgb_class)
print(f"AUC score: {xgb_auc}")

AUC score: 0.8850766677434503

# Normalize Numeric Features

In [54]:
def scale_features(df_num):
    from sklearn.preprocessing import StandardScaler
    df_std = StandardScaler().fit_transform(df_num)
    scaled = pd.DataFrame(df_std, columns=df_num.columns)
    return scaled

In [55]:
df_num_scaled = scale_features(df_num)

# Test run with scaled numeric features

Produced AUC of: 0.885040747954212

*lower than All augmented features not scaled*

In [57]:
df_full = pd.concat([df_num_scaled.reset_index(drop=True), df_cat.reset_index(drop=True), df['heart_disease']], axis=1)

dep_var_name = 'heart_disease'

X = df_full.drop([dep_var_name], axis=1)
y = df_full[dep_var_name]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


param_optimal = {
    'learning_rate':0.1,
    'n_estimators':140,
    'max_depth':6,
    'min_child_weight':4,
    'gamma':0,
    'subsample':0.65,
    'colsample_bytree':0.75,
    'objective':'binary:logistic',
    'scale_pos_weight':1,
    'seed':42    
}

xgb = XGBClassifier(**param_optimal).fit(X_train, y_train)

xgb_class = xgb.predict(X_test)

xgb_auc = roc_auc_score(y_test, xgb_class)
print(f"AUC score: {xgb_auc}")

AUC score: 0.885040747954212

# Catboost testing

My thoughts are that if baseline catboost shows promise, theres an avenue of binning the numeric variables into categorical and trying to tune a catboost model

In [62]:
from catboost import CatBoostClassifier

In [67]:
df_full = pd.concat([df_cat.reset_index(drop=True), df['heart_disease']], axis=1)

dep_var_name = 'heart_disease'

X = df_full.drop([dep_var_name], axis=1)
y = df_full[dep_var_name]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


cb = CatBoostClassifier(cat_features=list(df_cat.columns)).fit(X_train, y_train)

Learning rate set to 0.146849
0:	learn: 0.5792944	total: 304ms	remaining: 5m 4s
1:	learn: 0.5062719	total: 429ms	remaining: 3m 34s
2:	learn: 0.4593145	total: 510ms	remaining: 2m 49s
3:	learn: 0.4197269	total: 615ms	remaining: 2m 33s
4:	learn: 0.3859329	total: 724ms	remaining: 2m 24s
5:	learn: 0.3644625	total: 807ms	remaining: 2m 13s
6:	learn: 0.3498338	total: 931ms	remaining: 2m 12s
7:	learn: 0.3412356	total: 1.02s	remaining: 2m 6s
8:	learn: 0.3342671	total: 1.12s	remaining: 2m 3s
9:	learn: 0.3285210	total: 1.21s	remaining: 2m
10:	learn: 0.3246900	total: 1.3s	remaining: 1m 57s
11:	learn: 0.3218390	total: 1.39s	remaining: 1m 54s
12:	learn: 0.3199039	total: 1.48s	remaining: 1m 52s
13:	learn: 0.3183350	total: 1.56s	remaining: 1m 49s
14:	learn: 0.3172904	total: 1.64s	remaining: 1m 47s
15:	learn: 0.3164744	total: 1.74s	remaining: 1m 47s
16:	learn: 0.3157277	total: 1.85s	remaining: 1m 47s
17:	learn: 0.3152010	total: 1.93s	remaining: 1m 45s
18:	learn: 0.3148355	total: 2.02s	remaining: 1m 44s
19:	learn: 0.3145173	total: 2.12s	remaining: 1m 43s
20:	learn: 0.3142666	total: 2.22s	remaining: 1m 43s
21:	learn: 0.3140613	total: 2.3s	remaining: 1m 42s
22:	learn: 0.3139381	total: 2.39s	remaining: 1m 41s
23:	learn: 0.3138044	total: 2.5s	remaining: 1m 41s
24:	learn: 0.3137148	total: 2.58s	remaining: 1m 40s
25:	learn: 0.3136445	total: 2.67s	remaining: 1m 40s
26:	learn: 0.3135681	total: 2.76s	remaining: 1m 39s
27:	learn: 0.3135124	total: 2.87s	remaining: 1m 39s
28:	learn: 0.3134751	total: 2.96s	remaining: 1m 39s
29:	learn: 0.3134445	total: 3.05s	remaining: 1m 38s
30:	learn: 0.3134114	total: 3.15s	remaining: 1m 38s
31:	learn: 0.3133808	total: 3.24s	remaining: 1m 37s
32:	learn: 0.3133525	total: 3.32s	remaining: 1m 37s
33:	learn: 0.3133311	total: 3.41s	remaining: 1m 37s
34:	learn: 0.3133084	total: 3.56s	remaining: 1m 38s
35:	learn: 0.3132985	total: 3.65s	remaining: 1m 37s
36:	learn: 0.3132782	total: 3.74s	remaining: 1m 37s
37:	learn: 0.3132570	total: 3.83s	remaining: 1m 36s
38:	learn: 0.3132453	total: 3.94s	remaining: 1m 37s
39:	learn: 0.3132172	total: 4.02s	remaining: 1m 36s
40:	learn: 0.3132094	total: 4.13s	remaining: 1m 36s
41:	learn: 0.3132094	total: 4.18s	remaining: 1m 35s
42:	learn: 0.3131964	total: 4.27s	remaining: 1m 35s
43:	learn: 0.3131926	total: 4.37s	remaining: 1m 34s
44:	learn: 0.3131890	total: 4.46s	remaining: 1m 34s
45:	learn: 0.3131890	total: 4.51s	remaining: 1m 33s
46:	learn: 0.3131890	total: 4.56s	remaining: 1m 32s
47:	learn: 0.3131818	total: 4.66s	remaining: 1m 32s
48:	learn: 0.3131732	total: 4.75s	remaining: 1m 32s
49:	learn: 0.3131704	total: 4.82s	remaining: 1m 31s
50:	learn: 0.3131704	total: 4.9s	remaining: 1m 31s
51:	learn: 0.3131626	total: 4.98s	remaining: 1m 30s
52:	learn: 0.3131590	total: 5.07s	remaining: 1m 30s
53:	learn: 0.3131499	total: 5.16s	remaining: 1m 30s
54:	learn: 0.3131452	total: 5.26s	remaining: 1m 30s
55:	learn: 0.3131422	total: 5.37s	remaining: 1m 30s
56:	learn: 0.3131369	total: 5.5s	remaining: 1m 30s
57:	learn: 0.3131306	total: 5.6s	remaining: 1m 31s
58:	learn: 0.3131280	total: 5.7s	remaining: 1m 30s
59:	learn: 0.3131249	total: 5.79s	remaining: 1m 30s
60:	learn: 0.3131191	total: 5.88s	remaining: 1m 30s
61:	learn: 0.3131100	total: 5.97s	remaining: 1m 30s
62:	learn: 0.3131087	total: 6.06s	remaining: 1m 30s
63:	learn: 0.3131087	total: 6.14s	remaining: 1m 29s
64:	learn: 0.3131025	total: 6.25s	remaining: 1m 29s
65:	learn: 0.3130976	total: 6.34s	remaining: 1m 29s
66:	learn: 0.3130974	total: 6.42s	remaining: 1m 29s
67:	learn: 0.3130900	total: 6.5s	remaining: 1m 29s
68:	learn: 0.3130900	total: 6.58s	remaining: 1m 28s
69:	learn: 0.3130850	total: 6.67s	remaining: 1m 28s
70:	learn: 0.3130774	total: 6.77s	remaining: 1m 28s
71:	learn: 0.3130731	total: 6.88s	remaining: 1m 28s
72:	learn: 0.3130725	total: 6.95s	remaining: 1m 28s
73:	learn: 0.3130650	total: 7.04s	remaining: 1m 28s
74:	learn: 0.3130615	total: 7.13s	remaining: 1m 27s
75:	learn: 0.3130584	total: 7.22s	remaining: 1m 27s
76:	learn: 0.3130578	total: 7.31s	remaining: 1m 27s
77:	learn: 0.3130578	total: 7.41s	remaining: 1m 27s
78:	learn: 0.3130551	total: 7.54s	remaining: 1m 27s
79:	learn: 0.3130431	total: 7.69s	remaining: 1m 28s
80:	learn: 0.3130409	total: 7.84s	remaining: 1m 28s
81:	learn: 0.3130400	total: 7.95s	remaining: 1m 29s
82:	learn: 0.3130386	total: 8.08s	remaining: 1m 29s
83:	learn: 0.3130373	total: 8.2s	remaining: 1m 29s
84:	learn: 0.3130360	total: 8.31s	remaining: 1m 29s
85:	learn: 0.3130348	total: 8.4s	remaining: 1m 29s
86:	learn: 0.3130302	total: 8.5s	remaining: 1m 29s
87:	learn: 0.3130275	total: 8.62s	remaining: 1m 29s
88:	learn: 0.3130215	total: 8.76s	remaining: 1m 29s
89:	learn: 0.3130215	total: 8.85s	remaining: 1m 29s
90:	learn: 0.3130180	total: 8.97s	remaining: 1m 29s
91:	learn: 0.3130170	total: 9.1s	remaining: 1m 29s
92:	learn: 0.3130127	total: 9.2s	remaining: 1m 29s
93:	learn: 0.3130113	total: 9.34s	remaining: 1m 30s
94:	learn: 0.3130085	total: 9.46s	remaining: 1m 30s
95:	learn: 0.3130084	total: 9.55s	remaining: 1m 29s
96:	learn: 0.3130059	total: 9.68s	remaining: 1m 30s
97:	learn: 0.3130044	total: 9.79s	remaining: 1m 30s
98:	learn: 0.3130018	total: 9.93s	remaining: 1m 30s
99:	learn: 0.3130018	total: 9.99s	remaining: 1m 29s
100:	learn: 0.3129977	total: 10.1s	remaining: 1m 29s
101:	learn: 0.3129953	total: 10.2s	remaining: 1m 29s
102:	learn: 0.3129953	total: 10.3s	remaining: 1m 30s
103:	learn: 0.3129951	total: 10.4s	remaining: 1m 29s
104:	learn: 0.3129951	total: 10.5s	remaining: 1m 29s
105:	learn: 0.3129893	total: 10.6s	remaining: 1m 29s
106:	learn: 0.3129893	total: 10.7s	remaining: 1m 28s
107:	learn: 0.3129861	total: 10.8s	remaining: 1m 29s
108:	learn: 0.3129861	total: 10.9s	remaining: 1m 28s
109:	learn: 0.3129861	total: 10.9s	remaining: 1m 28s
110:	learn: 0.3129856	total: 11.1s	remaining: 1m 28s
111:	learn: 0.3129832	total: 11.2s	remaining: 1m 28s
112:	learn: 0.3129827	total: 11.3s	remaining: 1m 28s
113:	learn: 0.3129809	total: 11.4s	remaining: 1m 28s
114:	learn: 0.3129796	total: 11.5s	remaining: 1m 28s
115:	learn: 0.3129784	total: 11.6s	remaining: 1m 28s
116:	learn: 0.3129760	total: 11.8s	remaining: 1m 28s
117:	learn: 0.3129760	total: 11.9s	remaining: 1m 28s
118:	learn: 0.3129759	total: 12s	remaining: 1m 28s
119:	learn: 0.3129703	total: 12.1s	remaining: 1m 28s
120:	learn: 0.3129683	total: 12.2s	remaining: 1m 28s
121:	learn: 0.3129676	total: 12.3s	remaining: 1m 28s
122:	learn: 0.3129663	total: 12.5s	remaining: 1m 28s
123:	learn: 0.3129663	total: 12.6s	remaining: 1m 28s
124:	learn: 0.3129647	total: 12.8s	remaining: 1m 29s
125:	learn: 0.3129647	total: 12.9s	remaining: 1m 29s
126:	learn: 0.3129599	total: 13s	remaining: 1m 29s
127:	learn: 0.3129599	total: 13.1s	remaining: 1m 29s
128:	learn: 0.3129585	total: 13.2s	remaining: 1m 29s
129:	learn: 0.3129570	total: 13.3s	remaining: 1m 28s
130:	learn: 0.3129562	total: 13.4s	remaining: 1m 28s
131:	learn: 0.3129517	total: 13.5s	remaining: 1m 28s
132:	learn: 0.3129490	total: 13.6s	remaining: 1m 28s
133:	learn: 0.3129490	total: 13.8s	remaining: 1m 28s
134:	learn: 0.3129479	total: 13.9s	remaining: 1m 28s
135:	learn: 0.3129468	total: 14s	remaining: 1m 28s
136:	learn: 0.3129420	total: 14.1s	remaining: 1m 28s
137:	learn: 0.3129407	total: 14.2s	remaining: 1m 28s
138:	learn: 0.3129404	total: 14.3s	remaining: 1m 28s
139:	learn: 0.3129395	total: 14.4s	remaining: 1m 28s
140:	learn: 0.3129379	total: 14.5s	remaining: 1m 28s
141:	learn: 0.3129364	total: 14.6s	remaining: 1m 28s
142:	learn: 0.3129313	total: 14.7s	remaining: 1m 28s
143:	learn: 0.3129267	total: 14.8s	remaining: 1m 28s
144:	learn: 0.3129253	total: 15s	remaining: 1m 28s
145:	learn: 0.3129226	total: 15.1s	remaining: 1m 28s
146:	learn: 0.3129219	total: 15.2s	remaining: 1m 28s
147:	learn: 0.3129148	total: 15.3s	remaining: 1m 28s
148:	learn: 0.3129138	total: 15.4s	remaining: 1m 28s
149:	learn: 0.3129132	total: 15.5s	remaining: 1m 28s
150:	learn: 0.3129084	total: 15.7s	remaining: 1m 28s
151:	learn: 0.3129001	total: 15.8s	remaining: 1m 28s
152:	learn: 0.3128990	total: 15.9s	remaining: 1m 27s
153:	learn: 0.3128954	total: 16s	remaining: 1m 27s
154:	learn: 0.3128911	total: 16.1s	remaining: 1m 27s
155:	learn: 0.3128903	total: 16.2s	remaining: 1m 27s
156:	learn: 0.3128839	total: 16.4s	remaining: 1m 27s
157:	learn: 0.3128820	total: 16.5s	remaining: 1m 27s
158:	learn: 0.3128814	total: 16.6s	remaining: 1m 27s
159:	learn: 0.3128787	total: 16.7s	remaining: 1m 27s
160:	learn: 0.3128774	total: 16.8s	remaining: 1m 27s
161:	learn: 0.3128721	total: 16.9s	remaining: 1m 27s
162:	learn: 0.3128718	total: 17.1s	remaining: 1m 27s
163:	learn: 0.3128696	total: 17.2s	remaining: 1m 27s
164:	learn: 0.3128656	total: 17.3s	remaining: 1m 27s
165:	learn: 0.3128647	total: 17.4s	remaining: 1m 27s
166:	learn: 0.3128617	total: 17.5s	remaining: 1m 27s
167:	learn: 0.3128600	total: 17.6s	remaining: 1m 27s
168:	learn: 0.3128593	total: 17.8s	remaining: 1m 27s
169:	learn: 0.3128563	total: 17.9s	remaining: 1m 27s
170:	learn: 0.3128534	total: 18s	remaining: 1m 27s
171:	learn: 0.3128525	total: 18.2s	remaining: 1m 27s
172:	learn: 0.3128513	total: 18.3s	remaining: 1m 27s
173:	learn: 0.3128464	total: 18.4s	remaining: 1m 27s
174:	learn: 0.3128454	total: 18.5s	remaining: 1m 27s
175:	learn: 0.3128438	total: 18.7s	remaining: 1m 27s
176:	learn: 0.3128364	total: 18.8s	remaining: 1m 27s
177:	learn: 0.3128364	total: 18.9s	remaining: 1m 27s
178:	learn: 0.3128353	total: 19s	remaining: 1m 27s
179:	learn: 0.3128325	total: 19.1s	remaining: 1m 27s
180:	learn: 0.3128302	total: 19.2s	remaining: 1m 27s
181:	learn: 0.3128268	total: 19.4s	remaining: 1m 27s
182:	learn: 0.3128251	total: 19.5s	remaining: 1m 26s
183:	learn: 0.3128224	total: 19.6s	remaining: 1m 26s
184:	learn: 0.3128223	total: 19.7s	remaining: 1m 26s
185:	learn: 0.3128207	total: 19.8s	remaining: 1m 26s
186:	learn: 0.3128205	total: 19.9s	remaining: 1m 26s
187:	learn: 0.3128194	total: 20s	remaining: 1m 26s
188:	learn: 0.3128157	total: 20.2s	remaining: 1m 26s
189:	learn: 0.3128151	total: 20.3s	remaining: 1m 26s
190:	learn: 0.3128136	total: 20.4s	remaining: 1m 26s
191:	learn: 0.3128103	total: 20.5s	remaining: 1m 26s
192:	learn: 0.3128082	total: 20.6s	remaining: 1m 26s
193:	learn: 0.3128031	total: 20.8s	remaining: 1m 26s
194:	learn: 0.3127965	total: 20.9s	remaining: 1m 26s
195:	learn: 0.3127937	total: 21s	remaining: 1m 26s
196:	learn: 0.3127887	total: 21.1s	remaining: 1m 26s
197:	learn: 0.3127833	total: 21.2s	remaining: 1m 25s
198:	learn: 0.3127804	total: 21.3s	remaining: 1m 25s
199:	learn: 0.3127777	total: 21.5s	remaining: 1m 25s
200:	learn: 0.3127769	total: 21.6s	remaining: 1m 25s
201:	learn: 0.3127768	total: 21.7s	remaining: 1m 25s
202:	learn: 0.3127757	total: 21.8s	remaining: 1m 25s
203:	learn: 0.3127750	total: 21.8s	remaining: 1m 25s
204:	learn: 0.3127741	total: 21.9s	remaining: 1m 25s
205:	learn: 0.3127663	total: 22s	remaining: 1m 24s
206:	learn: 0.3127635	total: 22.1s	remaining: 1m 24s
207:	learn: 0.3127627	total: 22.2s	remaining: 1m 24s
208:	learn: 0.3127625	total: 22.3s	remaining: 1m 24s
209:	learn: 0.3127596	total: 22.4s	remaining: 1m 24s
210:	learn: 0.3127586	total: 22.5s	remaining: 1m 24s
211:	learn: 0.3127554	total: 22.6s	remaining: 1m 24s
212:	learn: 0.3127537	total: 22.7s	remaining: 1m 23s
213:	learn: 0.3127500	total: 22.8s	remaining: 1m 23s
214:	learn: 0.3127484	total: 22.9s	remaining: 1m 23s
215:	learn: 0.3127441	total: 23s	remaining: 1m 23s
216:	learn: 0.3127424	total: 23s	remaining: 1m 23s
217:	learn: 0.3127404	total: 23.1s	remaining: 1m 22s
218:	learn: 0.3127378	total: 23.2s	remaining: 1m 22s
219:	learn: 0.3127320	total: 23.3s	remaining: 1m 22s
220:	learn: 0.3127288	total: 23.4s	remaining: 1m 22s
221:	learn: 0.3127273	total: 23.5s	remaining: 1m 22s
222:	learn: 0.3127244	total: 23.6s	remaining: 1m 22s
223:	learn: 0.3127217	total: 23.7s	remaining: 1m 21s
224:	learn: 0.3127200	total: 23.7s	remaining: 1m 21s
225:	learn: 0.3127190	total: 23.8s	remaining: 1m 21s
226:	learn: 0.3127179	total: 23.9s	remaining: 1m 21s
227:	learn: 0.3127173	total: 24s	remaining: 1m 21s
228:	learn: 0.3127136	total: 24.1s	remaining: 1m 21s
229:	learn: 0.3127110	total: 24.2s	remaining: 1m 21s
230:	learn: 0.3127095	total: 24.3s	remaining: 1m 20s
231:	learn: 0.3127083	total: 24.4s	remaining: 1m 20s
232:	learn: 0.3127082	total: 24.5s	remaining: 1m 20s
233:	learn: 0.3127046	total: 24.6s	remaining: 1m 20s
234:	learn: 0.3127022	total: 24.7s	remaining: 1m 20s
235:	learn: 0.3127007	total: 24.7s	remaining: 1m 20s
236:	learn: 0.3126987	total: 24.8s	remaining: 1m 19s
237:	learn: 0.3126986	total: 24.9s	remaining: 1m 19s
238:	learn: 0.3126967	total: 25s	remaining: 1m 19s
239:	learn: 0.3126947	total: 25.1s	remaining: 1m 19s
240:	learn: 0.3126935	total: 25.2s	remaining: 1m 19s
241:	learn: 0.3126935	total: 25.3s	remaining: 1m 19s
242:	learn: 0.3126926	total: 25.4s	remaining: 1m 19s
243:	learn: 0.3126891	total: 25.5s	remaining: 1m 18s
244:	learn: 0.3126887	total: 25.6s	remaining: 1m 18s
245:	learn: 0.3126817	total: 25.6s	remaining: 1m 18s
246:	learn: 0.3126783	total: 25.7s	remaining: 1m 18s
247:	learn: 0.3126755	total: 25.8s	remaining: 1m 18s
248:	learn: 0.3126736	total: 25.9s	remaining: 1m 18s
249:	learn: 0.3126723	total: 26s	remaining: 1m 17s
250:	learn: 0.3126716	total: 26.1s	remaining: 1m 17s
251:	learn: 0.3126692	total: 26.2s	remaining: 1m 17s
252:	learn: 0.3126665	total: 26.3s	remaining: 1m 17s
253:	learn: 0.3126643	total: 26.3s	remaining: 1m 17s
254:	learn: 0.3126642	total: 26.4s	remaining: 1m 17s
255:	learn: 0.3126619	total: 26.5s	remaining: 1m 17s
256:	learn: 0.3126565	total: 26.6s	remaining: 1m 16s
257:	learn: 0.3126508	total: 26.7s	remaining: 1m 16s
258:	learn: 0.3126492	total: 26.8s	remaining: 1m 16s
259:	learn: 0.3126491	total: 26.9s	remaining: 1m 16s
260:	learn: 0.3126428	total: 27s	remaining: 1m 16s
261:	learn: 0.3126391	total: 27.1s	remaining: 1m 16s
262:	learn: 0.3126378	total: 27.2s	remaining: 1m 16s
263:	learn: 0.3126362	total: 27.3s	remaining: 1m 16s
264:	learn: 0.3126362	total: 27.4s	remaining: 1m 15s
265:	learn: 0.3126348	total: 27.5s	remaining: 1m 15s
266:	learn: 0.3126334	total: 27.6s	remaining: 1m 15s
267:	learn: 0.3126326	total: 27.6s	remaining: 1m 15s
268:	learn: 0.3126307	total: 27.7s	remaining: 1m 15s
269:	learn: 0.3126293	total: 27.8s	remaining: 1m 15s
270:	learn: 0.3126272	total: 27.9s	remaining: 1m 15s
271:	learn: 0.3126272	total: 28s	remaining: 1m 14s
272:	learn: 0.3126245	total: 28.1s	remaining: 1m 14s
273:	learn: 0.3126220	total: 28.2s	remaining: 1m 14s
274:	learn: 0.3126205	total: 28.3s	remaining: 1m 14s
275:	learn: 0.3126185	total: 28.4s	remaining: 1m 14s
276:	learn: 0.3126176	total: 28.5s	remaining: 1m 14s
277:	learn: 0.3126164	total: 28.6s	remaining: 1m 14s
278:	learn: 0.3126149	total: 28.6s	remaining: 1m 14s
279:	learn: 0.3126109	total: 28.7s	remaining: 1m 13s
280:	learn: 0.3126070	total: 28.8s	remaining: 1m 13s
281:	learn: 0.3126051	total: 28.9s	remaining: 1m 13s
282:	learn: 0.3126030	total: 29s	remaining: 1m 13s
283:	learn: 0.3126016	total: 29.1s	remaining: 1m 13s
284:	learn: 0.3125995	total: 29.2s	remaining: 1m 13s
285:	learn: 0.3125974	total: 29.3s	remaining: 1m 13s
286:	learn: 0.3125960	total: 29.4s	remaining: 1m 12s
287:	learn: 0.3125951	total: 29.4s	remaining: 1m 12s
288:	learn: 0.3125937	total: 29.5s	remaining: 1m 12s
289:	learn: 0.3125899	total: 29.6s	remaining: 1m 12s
290:	learn: 0.3125889	total: 29.7s	remaining: 1m 12s
291:	learn: 0.3125884	total: 29.8s	remaining: 1m 12s
292:	learn: 0.3125851	total: 29.9s	remaining: 1m 12s
293:	learn: 0.3125822	total: 30s	remaining: 1m 12s
294:	learn: 0.3125786	total: 30.1s	remaining: 1m 11s
295:	learn: 0.3125752	total: 30.2s	remaining: 1m 11s
296:	learn: 0.3125694	total: 30.3s	remaining: 1m 11s
297:	learn: 0.3125664	total: 30.4s	remaining: 1m 11s
298:	learn: 0.3125630	total: 30.5s	remaining: 1m 11s
299:	learn: 0.3125612	total: 30.5s	remaining: 1m 11s
300:	learn: 0.3125579	total: 30.6s	remaining: 1m 11s
301:	learn: 0.3125574	total: 30.7s	remaining: 1m 10s
302:	learn: 0.3125539	total: 30.8s	remaining: 1m 10s
303:	learn: 0.3125520	total: 30.9s	remaining: 1m 10s
304:	learn: 0.3125480	total: 31s	remaining: 1m 10s
305:	learn: 0.3125451	total: 31.1s	remaining: 1m 10s
306:	learn: 0.3125397	total: 31.2s	remaining: 1m 10s
307:	learn: 0.3125382	total: 31.2s	remaining: 1m 10s
308:	learn: 0.3125369	total: 31.3s	remaining: 1m 10s
309:	learn: 0.3125330	total: 31.4s	remaining: 1m 9s
310:	learn: 0.3125267	total: 31.5s	remaining: 1m 9s
311:	learn: 0.3125267	total: 31.6s	remaining: 1m 9s
312:	learn: 0.3125252	total: 31.7s	remaining: 1m 9s
313:	learn: 0.3125230	total: 31.8s	remaining: 1m 9s
314:	learn: 0.3125186	total: 31.9s	remaining: 1m 9s
315:	learn: 0.3125167	total: 32s	remaining: 1m 9s
316:	learn: 0.3125139	total: 32.1s	remaining: 1m 9s
317:	learn: 0.3125139	total: 32.1s	remaining: 1m 8s
318:	learn: 0.3125123	total: 32.2s	remaining: 1m 8s
319:	learn: 0.3125094	total: 32.3s	remaining: 1m 8s
320:	learn: 0.3125083	total: 32.4s	remaining: 1m 8s
321:	learn: 0.3125069	total: 32.5s	remaining: 1m 8s
322:	learn: 0.3125058	total: 32.6s	remaining: 1m 8s
323:	learn: 0.3125034	total: 32.7s	remaining: 1m 8s
324:	learn: 0.3125008	total: 32.8s	remaining: 1m 8s
325:	learn: 0.3124991	total: 32.9s	remaining: 1m 7s
326:	learn: 0.3124971	total: 33s	remaining: 1m 7s
327:	learn: 0.3124952	total: 33.1s	remaining: 1m 7s
328:	learn: 0.3124925	total: 33.1s	remaining: 1m 7s
329:	learn: 0.3124870	total: 33.2s	remaining: 1m 7s
330:	learn: 0.3124861	total: 33.3s	remaining: 1m 7s
331:	learn: 0.3124855	total: 33.4s	remaining: 1m 7s
332:	learn: 0.3124848	total: 33.5s	remaining: 1m 7s
333:	learn: 0.3124816	total: 33.6s	remaining: 1m 6s
334:	learn: 0.3124793	total: 33.7s	remaining: 1m 6s
335:	learn: 0.3124777	total: 33.7s	remaining: 1m 6s
336:	learn: 0.3124775	total: 33.8s	remaining: 1m 6s
337:	learn: 0.3124760	total: 33.9s	remaining: 1m 6s
338:	learn: 0.3124753	total: 34s	remaining: 1m 6s
339:	learn: 0.3124737	total: 34.1s	remaining: 1m 6s
340:	learn: 0.3124725	total: 34.2s	remaining: 1m 6s
341:	learn: 0.3124721	total: 34.3s	remaining: 1m 5s
342:	learn: 0.3124699	total: 34.4s	remaining: 1m 5s
343:	learn: 0.3124658	total: 34.5s	remaining: 1m 5s
344:	learn: 0.3124598	total: 34.6s	remaining: 1m 5s
345:	learn: 0.3124570	total: 34.7s	remaining: 1m 5s
346:	learn: 0.3124561	total: 34.8s	remaining: 1m 5s
347:	learn: 0.3124537	total: 34.9s	remaining: 1m 5s
348:	learn: 0.3124519	total: 35s	remaining: 1m 5s
349:	learn: 0.3124498	total: 35.1s	remaining: 1m 5s
350:	learn: 0.3124480	total: 35.2s	remaining: 1m 5s
351:	learn: 0.3124479	total: 35.3s	remaining: 1m 4s
352:	learn: 0.3124456	total: 35.4s	remaining: 1m 4s
353:	learn: 0.3124416	total: 35.5s	remaining: 1m 4s
354:	learn: 0.3124384	total: 35.6s	remaining: 1m 4s
355:	learn: 0.3124355	total: 35.6s	remaining: 1m 4s
356:	learn: 0.3124347	total: 35.7s	remaining: 1m 4s
357:	learn: 0.3124310	total: 35.8s	remaining: 1m 4s
358:	learn: 0.3124296	total: 35.9s	remaining: 1m 4s
359:	learn: 0.3124277	total: 36s	remaining: 1m 3s
360:	learn: 0.3124245	total: 36.1s	remaining: 1m 3s
361:	learn: 0.3124245	total: 36.2s	remaining: 1m 3s
362:	learn: 0.3124229	total: 36.3s	remaining: 1m 3s
363:	learn: 0.3124213	total: 36.4s	remaining: 1m 3s
364:	learn: 0.3124202	total: 36.4s	remaining: 1m 3s
365:	learn: 0.3124149	total: 36.5s	remaining: 1m 3s
366:	learn: 0.3124137	total: 36.6s	remaining: 1m 3s
367:	learn: 0.3124118	total: 36.7s	remaining: 1m 3s
368:	learn: 0.3124086	total: 36.8s	remaining: 1m 2s
369:	learn: 0.3124044	total: 36.9s	remaining: 1m 2s
370:	learn: 0.3124026	total: 36.9s	remaining: 1m 2s
371:	learn: 0.3124007	total: 37s	remaining: 1m 2s
372:	learn: 0.3123988	total: 37.1s	remaining: 1m 2s
373:	learn: 0.3123970	total: 37.2s	remaining: 1m 2s
374:	learn: 0.3123905	total: 37.3s	remaining: 1m 2s
375:	learn: 0.3123899	total: 37.4s	remaining: 1m 2s
376:	learn: 0.3123892	total: 37.5s	remaining: 1m 1s
377:	learn: 0.3123883	total: 37.6s	remaining: 1m 1s
378:	learn: 0.3123882	total: 37.6s	remaining: 1m 1s
379:	learn: 0.3123872	total: 37.7s	remaining: 1m 1s
380:	learn: 0.3123854	total: 37.8s	remaining: 1m 1s

In [68]:
cb_class = cb.predict(X_test)
cb_auc = roc_auc_score(y_test, cb_class)
print(f"AUC score: {cb_auc}")

AUC score: 0.8656589337166473